<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Kirill" failures="4" tests="21" name="Test" time="0.159" errors="0" timestamp="2020-04-13T22:12:03 MSK">
  <testcase classname="com.epam.testng.tests.CtgOfDoubleValueCalcTest" name="ctgOfDoubleValue" time="0.008">
    <failure type="java.lang.AssertionError" message="did not expect to find [1.00182542851] but found [0.9981778976111987]">
      <![CDATA[java.lang.AssertionError: did not expect to find [1.00182542851] but found [0.9981778976111987]
at com.epam.testng.tests.CtgOfDoubleValueCalcTest.ctgOfDoubleValue(CtgOfDoubleValueCalcTest.java:11)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- ctgOfDoubleValue -->
  <testcase classname="com.epam.testng.tests.CosOfDoubleValueCalcTest" name="cosOfDoubleValue" time="0.008">
    <failure type="java.lang.AssertionError" message="did not expect to find [-0.283691091486527] but found [0.9589157234143065]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-0.283691091486527] but found [0.9589157234143065]
at com.epam.testng.tests.CosOfDoubleValueCalcTest.cosOfDoubleValue(CosOfDoubleValueCalcTest.java:11)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- cosOfDoubleValue -->
  <testcase classname="com.epam.testng.tests.DivOfDoubleValuesCalcTest" name="divOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.DivOfLongValuesCalcTest" name="divOfTwoLongValues" time="0.002">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.epam.testng.tests.DivOfLongValuesCalcTest.divOfTwoLongValues(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: divOfTwoLongValues([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Long) 4,(java.lang.Integer) 0]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.epam.testng.tests.DivOfLongValuesCalcTest.divOfTwoLongValues(long,long,long)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: divOfTwoLongValues([Parameter{index=0, type=long, declaredAnnotations=[]}, Parameter{index=1, type=long, declaredAnnotations=[]}, Parameter{index=2, type=long, declaredAnnotations=[]}])
Arguments: [(java.lang.Long) 4,(java.lang.Integer) 0]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- divOfTwoLongValues -->
  <testcase classname="com.epam.testng.tests.IsNegativeCalcTest" name="isNegativeOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.IsPositiveCalcTest" name="isPositiveOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.IsNegativeCalcTest" name="isNegativeOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.IsPositiveCalcTest" name="isPositiveOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.IsNegativeCalcTest" name="isNegativeOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.IsPositiveCalcTest" name="isPositiveOfLongValue" time="0.0"/>
  <testcase classname="com.epam.testng.tests.MultOfLongValuesCalcTest" name="multOfTwoLongValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.MultOfDoubleValuesCalcTest" name="multOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.PowOfDoubleValuesCalcTest" name="powOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.PowOfDoubleValuesCalcTest" name="powOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.SinOfDoubleValueCalcTest" name="sinOfDoubleValue" time="0.001"/>
  <testcase classname="com.epam.testng.tests.SqrtOfDoubleValueCalcTest" name="sqrtOfDoubleValue" time="0.002"/>
  <testcase classname="com.epam.testng.tests.SubOfDoubleValuesCalcTest" name="subOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.SubOfLongValuesCalcTest" name="subOfTwoLongValues" time="0.001"/>
  <testcase classname="com.epam.testng.tests.SumOfDoubleValuesCalcTest" name="sumOfTwoDoubleValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.SumOfLongValuesCalcTest" name="sumOfTwoLongValues" time="0.0"/>
  <testcase classname="com.epam.testng.tests.TgOfDoubleValueCalcTest" name="tgOfDoubleValue" time="0.0">
    <failure type="java.lang.AssertionError" message="did not expect to find [-3.3801404139609623] but found [1.0]">
      <![CDATA[java.lang.AssertionError: did not expect to find [-3.3801404139609623] but found [1.0]
at com.epam.testng.tests.TgOfDoubleValueCalcTest.tgOfDoubleValue(TgOfDoubleValueCalcTest.java:11)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tgOfDoubleValue -->
</testsuite> <!-- Test -->
